### ISSUE TITLE
ERROR: Could not build wheels for lang-sam, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by zhanglixuan0720** [luca-medeiros/lang-segment-anything#13]
## Instructions To Reproduce the 🐛 Bug:

1. I run the command 
```
pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git
```
but get the error :
```
Building wheels for collected packages: lang-sam, groundingdino, segment-anything
  Building wheel for lang-sam (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for lang-sam (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      Traceback (most recent call last):
        File "/home/vismod/anaconda3/envs/segment/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/vismod/anaconda3/envs/segment/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/vismod/anaconda3/envs/segment/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 56, in build_wheel
          return WheelBuilder.make_in(
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 85, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 121, in build
          self._copy_module(zip_file)
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 232, in _copy_module
          to_add = self.find_files_to_add()
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/builder.py", line 198, in find_files_to_add
          if self.is_excluded(
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/builder.py", line 144, in is_excluded
          if exclude_path.as_posix() in self.find_excluded_files(fmt=self.format):
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/builder.py", line 112, in find_excluded_files
          vcs_ignored_files = set(vcs.get_ignored_files())
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/vcs/git.py", line 340, in get_ignored_files
          output = self.run(*args)
        File "/tmp/pip-build-env-w3hevfp7/overlay/lib/python3.8/site-packages/poetry/core/vcs/git.py", line 372, in run
          subprocess.check_output(
        File "/home/vismod/anaconda3/envs/segment/lib/python3.8/subprocess.py", line 415, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/vismod/anaconda3/envs/segment/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['git', '--git-dir', '14:55:53.637805 git.c:439               trace: built-in: git rev-parse --show-toplevel\n/tmp/pip-req-build-y5hh1atw/.git', '--work-tree', '14:55:53.637805 git.c:439               trace: built-in: git rev-parse --show-toplevel\n/tmp/pip-req-build-y5hh1atw', 'ls-files', '--others', '-i', '--exclude-standard']' returned non-zero exit status 128.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lang-sam
  Building wheel for groundingdino (setup.py) ... done
  Created wheel for groundingdino: filename=groundingdino-0.1.0-cp38-cp38-linux_x86_64.whl size=3894296 sha256=babeb3fe546ebc022b53ce9e2cd9c2e6e2309792f384e48d5ba7d5bab3138703
  Stored in directory: /tmp/pip-ephem-wheel-cache-f7dkjaf5/wheels/d3/f5/df/db4a813287ee7ae962a814f62e14d1e48173cad8f2f9100e9b
  Building wheel for segment-anything (setup.py) ... done
  Created wheel for segment-anything: filename=segment_anything-1.0-py3-none-any.whl size=36587 sha256=9f826654d1f77bca918a052243539bf96c9467538d418690bf557b29a0c4bcf7
  Stored in directory: /tmp/pip-ephem-wheel-cache-f7dkjaf5/wheels/b0/7e/40/20f0b1e23280cc4a66dc8009c29f42cb4afc1b205bc5814786
Successfully built groundingdino segment-anything
Failed to build lang-sam
ERROR: Could not build wheels for lang-sam, which is required to install pyproject.toml-based projects
```

## Expected behavior:

how can I fix the bug?

## Environment:

Python: 3.8.16
torch: '2.0.0+cu117'
torchvision: '0.15.1+cu117'

**Comment by ardaOnal** [comment]
+1 Experienced a similar error while trying install.

**Comment by yhw2003** [comment]
use cuda 11.5 instead of 11.7 (-> & <-)

**Comment by WASasquatch** [comment]
Oh, so suppose cuda 11.8 is out to?

**Comment by wm-mask** [comment]
You still need a `setup.py` file alongside the `.toml` file.
Refer to this solution here that describes well how to do it 👉 : https://stackoverflow.com/a/62983901/6786975

**Comment by WASasquatch** [comment]
> You still need a `setup.py` file alongside the `.toml` file. Refer to this solution here that describes well how to do it 👉 : https://stackoverflow.com/a/62983901/6786975

The issue here is building wheels, and specifically in my case, it has a setup.py

**Comment by anmorgan24** [comment]
Also getting this error and none of the suggested solutions have worked for me.

I also tried removing the -U flag included in the README setup and it fixed this issue, but created other dependency errors.

**Comment by gonultasbu** [comment]
Installing GroundingDINO before triggering the install of this package solved the issue for me for Python 3.10. GroundingDINO installation was not straightforward but works if you install torch using this method: https://github.com/IDEA-Research/GroundingDINO/issues/114#issuecomment-1586489432.

**Comment by gonultasbu** [comment]
Has anyone been able to solve this issue? To me it looks like a dependency problem but I have hard time figuring out which Python, torchvision and CUDA versions to pick for this repository to work without issues.

**Comment by PeaceNeil** [comment]
Just sharing my my installation process:
Environment: ubuntu 22.04.3 python3.8 cuda 11.8
```
pip install torch==2.1.1 torchvision==0.16.1 torchaudio==2.1.1 --index-url https://download.pytorch.org/whl/cu118
git clone https://github.com/IDEA-Research/GroundingDINO.git
cd GroundingDINO/
pip install -e .
```
return to the project directory
```
git clone https://github.com/luca-medeiros/lang-segment-anything && cd lang-segment-anything
pip install -e .
```

**Comment by Wenbobobo** [comment]
i've tried conda\pip\poety and spent nearly a week on this....😭
Is there a way to pack it as a docker? It may helps a lot

**Comment by luca-medeiros** [comment]
@Wenbobobo mind uploading your specs and cuda version?

**Comment by Bella722** [comment]
I successfully installed and ran the inference on windows, here are my installation steps and the inference scripts
`conda creat --name text_sam python=3.11
conda activate text_sam
pip install torch==2.4.1 torchvision==0.19.1 --extra-index-url https://download.pytorch.org/whl/cu124
git clone https://github.com/luca-medeiros/lang-segment-anything && cd lang-segment-anything`
then edit requirements.txt， replace uvloop as winloop
continue  run commnd will succeed
`pip install -e .`
and my inference.py is
`from PIL import Image
from lang_sam import LangSAM
import numpy as np
import os
import traceback
from lang_sam.utils import draw_image

def process_image(input_image_path: str):
    try:
        # 读取输入图像
        image_pil = Image.open(input_image_path).convert("RGB")

        # 设置文本提示
        text_prompt = "roof."

        # 进行预测
        results = model.predict([image_pil], [text_prompt])
        results = results[0]

        # 将图像转换为 NumPy 数组
        image_array = np.asarray(image_pil)

        # 绘制结果图像
        output_image = draw_image(
            image_array,
            results["masks"],
            results["boxes"],
            results["scores"],
            results["labels"],
        )

        # 将 NumPy 数组转换为 PIL 图像并保存为 RGB 格式
        output_image = Image.fromarray(np.uint8(output_image)).convert("RGB")

        # 获取输入图像文件名（不包含扩展名）和路径
        file_name = os.path.splitext(os.path.basename(input_image_path))[0]
        file_dir = os.path.dirname(input_image_path)

        # 设置保存的文件路径（与输入文件同名但不同扩展名）
        output_file = os.path.join(file_dir, f'{file_name}_combined_mask.png')

        # 保存结果图像
        output_image.save(output_file)
        print(f"Image saved as {output_file}")

    except:
        traceback.print_exc()


# 加载模型
model = LangSAM()
# 调用函数并传入输入图像路径
process_image(r"assets\roof.tif")`

my blog with more detail https://zhuanlan.zhihu.com/p/1612239029?utm_psn=1830308740735328256
