### ISSUE TITLE
fine-tune with labelled images

### ISSUE THREAD

**Issue by jialeqian** [luca-medeiros/lang-segment-anything#18]
## 🚀 Feature

Very nice job! If some labelled images corresponding to the text can be put into the model to fine-tune, it will be better. Expect to your improved version!

**Comment by luca-medeiros** [comment]
Thanks! worked a bit on the labeling feature on this branch [f/labeling](https://github.com/luca-medeiros/lang-segment-anything/tree/f/labeling)
