### ISSUE TITLE
name '_c' is not defined

### ISSUE THREAD

**Issue by yaoleia** [luca-medeiros/lang-segment-anything#19]
## Instructions To Reproduce the 🐛 Bug:

```
lightning run app app.py
```
then trigger predict

Get Error:
name '_c' is not defined

## Environment:

- linux conda
- python3.8.10

**Comment by ShuhaoYuan** [comment]
I got the same error

**Comment by luca-medeiros** [comment]
Duplicated https://github.com/luca-medeiros/lang-segment-anything/issues/5
