### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by fsalmasri** [luca-medeiros/lang-segment-anything#21]
I tried using pip and cloning the project and I still have the same error. knowing that I have torch and torchvision installed. 

Python 3.10.9
torch 2.0.1+cu118
torchvision 0.15.2+cu118

**Comment by davidshhh** [comment]
running into this as well

**Comment by J0ELh** [comment]
The temporary solution I found was to use the non-cuda version of torch and torchvision

**Comment by jonahsamost** [comment]
was able to get it working with:
# groundingdino = {git = "https://github.com/IDEA-Research/GroundingDINO.git"}
groundingdino-py = "0.4.0"

in the pyproject.toml file

**Comment by luca-medeiros** [comment]
#49
