### ISSUE TITLE
how to fill in the text_prompt for some uncommon categories?

### ISSUE THREAD

**Issue by y200504040u** [luca-medeiros/lang-segment-anything#23]
Thanks for your great works!
I got perfect results.
Can you provide a dictionary containing the supported categories to show me which text I can fill in？
Looking forward to your answer.
Thanks.

**Comment by luca-medeiros** [comment]
There isn't such a thing as a dictionary of supported categories. GroundingDino is a zero-shot model. Might be helpful to check their paper/repo https://github.com/IDEA-Research/GroundingDINO

**Comment by pzhren** [comment]
Hi:
What is the difference between lang-segment-anything and GroundingDINO+SAM?
