### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by askerlee** [luca-medeiros/lang-segment-anything#26]
Run a simple example and got "Error". The terminal doesn't print any error messages.

![image](https://github.com/luca-medeiros/lang-segment-anything/assets/1575461/b2f6edd3-701e-41dc-9cee-888dedda48f1)

Any ideas how to debug it? Thanks. I tried to set a breakpoint at predict() but it doesn't trigger when I clicked "Submit".

**Comment by viiika** [comment]
Me met the same problem.

**Comment by luca-medeiros** [comment]
That is quite strange. Guess we should do some debugging to find the culprit. 
Mind posting more details about your GPU, cuda version, etc?

**Comment by Noyii** [comment]
Thanks for your reply. My GPU is A100 80GB and cuda version is 11.8, and I reinstalled my torch and lang-segment-anything, now it works. One thing worth to comment is I replace 
```powershell
pip install torch torchvision
pip install -e .
``` 
with
```powershell
pip3 install torch torchvision
pip3 install -e .
```
which should be my environment problems.
