### ISSUE TITLE
Custom Checkpoints

### ISSUE THREAD

**Issue by KabirSubbiah** [luca-medeiros/lang-segment-anything#27]
Hi @luca-medeiros,

Great work! I was using the model and thought it would be useful if LangSAM() accepted a SAM ckpt as an argument. This would allow for other checkpoints like HQ_SAM to be included more easily. Also, for people who have downloaded the model and are working in Colab, this would free up memory.

Happy to help!

Thanks,

Kabir

**Comment by luca-medeiros** [comment]
Hey @KabirSubbiah thanks
That sounds like a nice feature! Wanna write a pr?

**Comment by KabirSubbiah** [comment]
Done,

Let me know if any changes need to be made!
