### ISSUE TITLE
Speed improvement

### ISSUE THREAD

**Issue by pwichmann** [luca-medeiros/lang-segment-anything#29]
## 🚀 Feature

Is there a way to speed up the segmentation process?

## Motivation & Examples

I noticed that my machine was not utilised much (GPU utilization < 20%, RAM and CPU were used to an even lesser degree) but segmenting a single large image took > 90 seconds. That is way too long for segmenting a large number of images.

I would think that there must be enormous potential for speed ups.

**Comment by pwichmann** [comment]
Forgot to say THANK YOU for an awesome library!

**Comment by luca-medeiros** [comment]
90 sec indeed sounds like a lot. It takes 3s or less for me on T4 and A100.
Mind sharing your specs and cuda version?
I'm guessing you are running on a CPU by mistake.

**Comment by Liquidmasl** [comment]
> 90 sec indeed sounds like a lot. It takes 3s or less for me on T4 and A100. Mind sharing your specs and cuda version? I'm guessing you are running on a CPU by mistake.

I am indeed running on CPU, I get the message in the console that it is just running on CPU, but i am not sure whats the reason. 
after some searching around it seams i am using the wrong CUDA version? or just a different cuda version that which what version torch was built. 
Can you help me out how I could solve that? 
In the end I want to be able to run my segmentation code in a docker container

**Comment by luca-medeiros** [comment]
@Liquidmasl 
uninstall torch and torchvision, and install again with the right cuda version.

**Comment by Liquidmasl** [comment]
> @Liquidmasl uninstall torch and torchvision, and install again with the right cuda version.

yeah i am a bit cautios with playing around with those versions, those changes dont quite like to stay in their own conda env somehow.

anyway i got it to run in docker, and now its crazy much faster, so thats nice!

**Comment by luca-medeiros** [comment]
Awesome! @Liquidmasl 

Closing for now.

**Comment by jwahnn** [comment]
How did you guys make it use GPU? I am facing a situation where it takes 20-30 seconds to process one image.
