### ISSUE TITLE
PR proposal dockerfile example

### ISSUE THREAD

**Issue by yachty66** [luca-medeiros/lang-segment-anything#33]
ive got the model running in a docker container. should i do a pull request? might be helpful to others. should i put it in the readme?

**Comment by im2ex** [comment]
Yes please do this. Would be helpful for me :-)  I struggle to get the model running.
(Already helpful as unmerged PR since anybody can decide to merge in locally)

**Comment by luca-medeiros** [comment]
A PR with readme mention would be very welcomed. Cheers!

**Comment by im2ex** [comment]
@yachty66 : I would be very thankful if you released what you have.
Otherwise I need to start from scratch and redoing the work (so even if there are still issues, a PR would be appreciated. I would work from there on then.)

**Comment by yachty66** [comment]
sorry. i was thinking of bringing this dockerfile out today but then didn't get to it and am now not following the project anymore.
