### ISSUE TITLE
Cannot install requirements

### ISSUE THREAD

**Issue by rohanopalai** [luca-medeiros/lang-segment-anything#4]
pip install -e .

Obtaining file:///Users/rohanrony/Documents/codeEnv/sam/lang-segment-anything
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting groundingdino@ git+ssh://git@github.com/IDEA-Research/GroundingDINO.git
  Cloning ssh://****@github.com/IDEA-Research/GroundingDINO.git to /private/var/folders/n2/h8y026vd7b3dnls6bt6xq70r0000gn/T/pip-install-3mgmt814/groundingdino_cf5f9106ff824b6689ce9f7436d0ab93
  Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/IDEA-Research/GroundingDINO.git' /private/var/folders/n2/h8y026vd7b3dnls6bt6xq70r0000gn/T/pip-install-3mgmt814/groundingdino_cf5f9106ff824b6689ce9f7436d0ab93
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet 'ssh://****@github.com/IDEA-Research/GroundingDINO.git' /private/var/folders/n2/h8y026vd7b3dnls6bt6xq70r0000gn/T/pip-install-3mgmt814/groundingdino_cf5f9106ff824b6689ce9f7436d0ab93 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet 'ssh://****@github.com/IDEA-Research/GroundingDINO.git' /private/var/folders/n2/h8y026vd7b3dnls6bt6xq70r0000gn/T/pip-install-3mgmt814/groundingdino_cf5f9106ff824b6689ce9f7436d0ab93 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by luca-medeiros** [comment]
@rohanopalai 
As your error msg says
```
[git@github.com](mailto:git@github.com): Permission denied (publickey).
fatal: Could not read from remote repository.
```
You probably don't have an [ssh key setup](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) properly. Might wanna try installing groundingdino and all the requirements separately.

**Comment by luca-medeiros** [comment]
@rohanopalai 
Updated dependencies from ssh to https
