### ISSUE TITLE
Load samhq model?

### ISSUE THREAD

**Issue by crapthings** [luca-medeiros/lang-segment-anything#45]
https://github.com/SysCV/sam-hq#model-checkpoints

https://huggingface.co/lkeab/hq-sam/tree/main

how to load sam_hq model?

**Comment by luca-medeiros** [comment]
Hey
https://github.com/luca-medeiros/lang-segment-anything#usage
here you can find custom checkpoint usage. havent test your case tho

**Comment by CkShibit** [comment]
![image](https://github.com/luca-medeiros/lang-segment-anything/assets/71413532/9ea5f1f3-8233-4734-87d3-71e2ffcb7cd5)
How to soulve the problem??

**Comment by luca-medeiros** [comment]
Hey, I think I found the issue.
https://github.com/luca-medeiros/lang-segment-anything/blob/134a48a81ebd691686187ecce2d016fb327a8852/lang_sam/lang_sam.py#L76
I believe here should be:
` sam = sam_model_registry[self.sam_type](checkpoint=ckpt_path)`

Mind trying and writing a PR if it works?
