### ISSUE TITLE
When running the predict line I'm getting that issue.

### ISSUE THREAD

**Issue by arslanahmad90** [luca-medeiros/lang-segment-anything#5]
![image](https://user-images.githubusercontent.com/80983846/232249492-f5b13d2d-860e-430a-9478-60dc232f9765.png)

**Comment by luca-medeiros** [comment]
@arslanahmad90 
Hey, have you installed torch and torchvision?
https://colab.research.google.com/drive/1e8bhnrmaWFkX6Z9KK5A4IOrJQaZwU2aO?usp=sharing

**Comment by VladimirKravtsov36** [comment]
> @arslanahmad90 Hey, have you installed torch and torchvision? https://colab.research.google.com/drive/1e8bhnrmaWFkX6Z9KK5A4IOrJQaZwU2aO?usp=sharing

I have installed torch and torchvision, got same error

**Comment by luca-medeiros** [comment]
Hey @VladimirKravtsov36 thanks for trying it out. That's strange.. 
Mind sharing your cuda/torch version? Did you try running on a CPU?

**Comment by algvr** [comment]
I was able to resolve this issue by manually reinstalling torch and torchvision using wheels from https://download.pytorch.org/whl/torch and https://download.pytorch.org/whl/torchvision (see https://github.com/pytorch/vision for a list of torch versions and corresponding torchvision versions).

**Comment by NimrodShabtay** [comment]
Same here,
I tried to re-install `torch 2.0.0` and the corresponded `torchvision` version but it didn't solve the issue

**Comment by algvr** [comment]
I used `torch==1.10.0+cu113` and `torchvision==0.11.1+cu113`, if it helps.

**Comment by vinesmsuic** [comment]
encountered same error
```
pip list | grep torch

pytorch-lightning        2.0.1.post0
torch                    2.0.0
torchaudio               2.0.0
torchmetrics             0.11.4
torchvision              0.15.0
```

**Comment by luca-medeiros** [comment]
tested and its working with torch2.0.0 and torchvision0.15.1.

**Comment by vinesmsuic** [comment]
mind sharing a `environment.yml` if you are using conda?

**Comment by vinesmsuic** [comment]
I found the problem is related to https://github.com/IDEA-Research/Grounded-Segment-Anything/issues/15 . Configuring $CUDA_HOME and install the package again solve the issue.
