### ISSUE TITLE
ERROR: No matching distribution found for groundingdinoPlease read & provide the following

### ISSUE THREAD

**Issue by SiyuYan02** [luca-medeiros/lang-segment-anything#51]
## Instructions To Reproduce the 🐛 Bug:

When I want to get the environment installed, I meet the error:
ERROR: Could not find a version that satisfies the requirement groundingdino (from versions: none)
ERROR: No matching distribution found for groundingdino

how can I fix this

**Comment by s183898** [comment]
My problem turned out to be mentioned on installation guide for groundingdino.

**Comment by CatDroid** [comment]
`
Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement groundingdino==0.1.0 (from versions: none)
ERROR: No matching distribution found for groundingdino==0.1.0
`

I meet the same problem .
it seems  groundingdino version 0.1.0 not exists ?  and groundingdino  version 1.2.0 require python 3.9 ?

**Comment by CatDroid** [comment]
Branch: main
Commit: f4ca2960a97cb73aff2c459a9d0f06c7674452e4
 `
ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement lang-sam==0.1.0 (from versions: none)
ERROR: No matching distribution found for lang-sam==0.1.0
`

 package lang-sam==0.1.0  not in pipy or conda-forge source  ?

**Comment by liuwenxin0410** [comment]
I successfully installed it with the following command.
Installation:

1.Clone the GroundingDINO repository from GitHub.

git clone https://github.com/IDEA-Research/GroundingDINO.git

Change the current directory to the GroundingDINO folder.

cd GroundingDINO/

Install the required dependencies in the current directory.
pip install -e .

**Comment by liuwenxin0410** [comment]
But In lang_sam.py file, I detect that the model = build_model(args) command of the load_model_hf function cannot be executed. why?thank you

**Comment by TimeChloe** [comment]
You can try pip install nw-groundingdino, this works for me.

**Comment by shaform** [comment]
I also encounter the same issue. It seems that the conda env use python 3.8, but some of the required packages do not support python 3.8 anymore.
