### ISSUE TITLE
Does not support Python3.10

### ISSUE THREAD

**Issue by plutonic89** [luca-medeiros/lang-segment-anything#56]
1. Background explanation

During installation I used python3.10. I got an error 

ERROR: Package 'lang-sam' requires a different Python: 3.11.5 not in '<3.11,>=3.8'

1. Full runnable code or full changes you made:

I changed the dependency in the environment.yml file. I used the following

  - python=3.10.12=h955ad1f_0

instead of python3.8

3. What exact command you run:

pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git

**Comment by mzg0108** [comment]
I have python 3.7.9 and I got the error
_**ERROR: Package 'lang-sam' requires a different Python: 3.7.9 not in '>=3.8,<3.11'**_

**Comment by luca-medeiros** [comment]
make sure your python is 3.8~3.10.
