### ISSUE TITLE
How to make it run on GPU/CUDA?

### ISSUE THREAD

**Issue by jwahnn** [luca-medeiros/lang-segment-anything#59]
When I try to run the model, the entire process takes about 20-30 seconds.

import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

Shows that I am using cuda, but I am expecting it to take less than 10 seconds on my V100 GPU.

**Comment by t5862755** [comment]
same question

**Comment by skulshreshtha** [comment]
I think the SAM part should be running on CUDA if you have it but the GroundingDINO part is not configured in the project to use the correct device. It uses CPU by default as the device argument to this function is not passed.
https://github.com/luca-medeiros/lang-segment-anything/blob/831cdc10906a23aabe4591a4be06f4c989e4ee30/lang_sam/lang_sam.py#L89

https://github.com/luca-medeiros/lang-segment-anything/blob/831cdc10906a23aabe4591a4be06f4c989e4ee30/lang_sam/lang_sam.py#L24

**Comment by vietvo89** [comment]
If you follow the instruction to set the right path `echo 'export CUDA_HOME=/usr/local/cuda' >> ~/.bashrc` as in https://github.com/IDEA-Research/GroundingDINO, you should be able to run on GPU. You may need to replace `cuda` with your cuda version e.g. `cuda-11.8`.
