### ISSUE TITLE
Installation stopped working after GroundingDino Update

### ISSUE THREAD

**Issue by tgrigat** [luca-medeiros/lang-segment-anything#66]
When trying to install the package using the steps of the documentation you get conflicting dependencies of lang-sam and grounding dino.
Root of the issue seems to be that the requirements of grounding dino were recently changed to force an installation of supervision 0.21.0 which is incompatible with pillow<9.4.

Theproblem is that lang-sam 0.1.0 depends on Pillow==9.3.0

I tried cuda and pip isntallation and it is for both the same.

**Comment by sd0809** [comment]
the same problem

**Comment by lhy0807** [comment]
same problem

**Comment by RabbitDF** [comment]
I have the same problem. Is there a solution?

**Comment by lhy0807** [comment]
A quick workaround: install GroundingDINO manually using [this commit version](https://github.com/IDEA-Research/GroundingDINO/tree/df5b48a3efbaa64288d8d0ad09b748ac86f22671)

**Comment by starry521** [comment]
Install locally and modify the pillow version number in the peoject.toml file
