### ISSUE TITLE
I am unable to import the module now.

### ISSUE THREAD

**Issue by MistyDragon7** [luca-medeiros/lang-segment-anything#67]
## Instructions To Reproduce the 🐛 Bug:

Forked the repo to my own account. Installed the module without errors. Then I ran the following:

`from lang_sam import LangSAM`
Immediately gave me an error. The error received seems to have no cause at all:
## Error
ImportError                               Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1352         try:
-> 1353             return importlib.import_module("." + module_name, self.__name__)
   1354         except Exception as e:

32 frames

ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)

RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)

[/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1353             return importlib.import_module("." + module_name, self.__name__)
   1354         except Exception as e:
-> 1355             raise RuntimeError(
   1356                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
   1357                 f" traceback):\n{e}"

RuntimeError: Failed to import transformers.models.bert.modeling_bert because of the following error (look up to see its traceback):
Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)

### Please help me resolve this to the earliest.

**Comment by YuxinYao620** [comment]
Hi, I have the same problem, may I ask did you solve it? Thank you!

**Comment by MistyDragon7** [comment]
Yes I did, I also made a pull request to fix the issue; it's upto the repository owner to accept the PR now.

**Comment by just1nseo** [comment]
@MistyDragon7 I am also having a same issue. Why did you close the issue ? Did you solve it? If you did, how ?

**Comment by MistyDragon7** [comment]
I have fixed it, and my changes have been merged to the main repo, that is why.
