### ISSUE TITLE
software conflict

### ISSUE THREAD

**Issue by xuyanging** [luca-medeiros/lang-segment-anything#69]
## Instructions To Reproduce the 🐛 Bug:

 I try to run pip install -e . ,but it seems some conflicts. please help me

![image](https://github.com/user-attachments/assets/59a9a868-4f3c-43f1-8b90-0e27743fa957)

**Comment by SridhanyaG** [comment]
yes i am also facing same please help

**Comment by darshanhegde** [comment]
yes, I also have the same problem.

**Comment by MistyDragon7** [comment]
I believe I have fixed this issue, if yes then please close it

**Comment by mudomau** [comment]
These were the ones causing the issue for me:

supervision >= 0.22.0 (current 0.6.0)
pillow == 9.4.0 (current 9.3.0)
huggingface-hub == 0.23.5 (current 0.13.4)
lightning >= 2.3.3 <3.0.0 (current 2.0.5)
transformers<5.0.0 and >=4.42.4 (current 4.2.4)
lightning-utilities>=0.10.0 (current 0.9.0)
safetensors>=0.4.1 (current 0.3.1)
tokenizers<0.20 and >=0.19 (current 0.13.3)

After changing them I was able to complete the install, but I still had a different issue - Grounding DINO is not loading.

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 2
      1 from PIL import Image
----> 2 from lang_sam import LangSAM
      3 import os
      4 import torch

File ~/Documents/Projects/Jupyter/segment-anything/lang-segment-anything/lang_sam/__init__.py:1
----> 1 from lang_sam.lang_sam import LangSAM
      2 from lang_sam.lang_sam import SAM_MODELS

File ~/Documents/Projects/Jupyter/segment-anything/lang-segment-anything/lang_sam/lang_sam.py:6
      4 import numpy as np
      5 import torch
----> 6 from groundingdino.models import build_model
      7 from groundingdino.util import box_ops
      8 from groundingdino.util.inference import predict

File ~/.conda/envs/lsa/lib/python3.8/site-packages/groundingdino/models/__init__.py:8
      1 # ------------------------------------------------------------------------
      2 # Grounding DINO
      3 # url: https://github.com/IDEA-Research/GroundingDINO
   (...)
      6 # ------------------------------------------------------------------------
      7 # Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
----> 8 from .GroundingDINO import build_groundingdino
     11 def build_model(args):
     12     # we use register to maintain models from catdet6 on.
     13     from .registry import MODULE_BUILD_FUNCS

File ~/.conda/envs/lsa/lib/python3.8/site-packages/groundingdino/models/GroundingDINO/__init__.py:15
      1 # ------------------------------------------------------------------------
      2 # Grounding DINO
      3 # url: https://github.com/IDEA-Research/GroundingDINO
   (...)
     12 # Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
     13 # ------------------------------------------------------------------------
---> 15 from .groundingdino import build_groundingdino

File ~/.conda/envs/lsa/lib/python3.8/site-packages/groundingdino/models/GroundingDINO/groundingdino.py:24
     22 from torch import nn
     23 from torchvision.ops.boxes import nms
---> 24 from transformers import AutoTokenizer, BertModel, BertTokenizer, RobertaModel, RobertaTokenizerFast
     26 from groundingdino.util import box_ops, get_tokenlizer
     27 from groundingdino.util.misc import (
     28     NestedTensor,
     29     accuracy,
   (...)
     34     nested_tensor_from_tensor_list,
     35 )

File ~/.conda/envs/lsa/lib/python3.8/site-packages/transformers/__init__.py:26
     23 from typing import TYPE_CHECKING
     25 # Check the dependencies satisfy the minimal versions required.
---> 26 from . import dependency_versions_check
     27 from .utils import (
     28     OptionalDependencyNotAvailable,
     29     _LazyModule,
   (...)
     48     logging,
     49 )
     52 logger = logging.get_logger(__name__)  # pylint: disable=invalid-name

File ~/.conda/envs/lsa/lib/python3.8/site-packages/transformers/dependency_versions_check.py:16
      1 # Copyright 2020 The HuggingFace Team. All rights reserved.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
     15 from .dependency_versions_table import deps
---> 16 from .utils.versions import require_version, require_version_core
     19 # define which module versions we always want to check at run time
     20 # (usually the ones defined in `install_requires` in setup.py)
     21 #
     22 # order specific notes:
     23 # - tqdm must be checked before tokenizers
     25 pkgs_to_check_at_runtime = [
     26     "python",
     27     "tqdm",
   (...)
     37     "pyyaml",
     38 ]

File ~/.conda/envs/lsa/lib/python3.8/site-packages/transformers/utils/__init__.py:34
     25 from .constants import IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD, IMAGENET_STANDARD_MEAN, IMAGENET_STANDARD_STD
     26 from .doc import (
     27     add_code_sample_docstrings,
     28     add_end_docstrings,
   (...)
     32     replace_return_docstrings,
     33 )
---> 34 from .generic import (
     35     ContextManagers,
     36     ExplicitEnum,
     37     ModelOutput,
     38     PaddingStrategy,
     39     TensorType,
     40     add_model_info_to_auto_map,
     41     add_model_info_to_custom_pipelines,
     42     cached_property,
     43     can_return_loss,
     44     expand_dims,
     45     filter_out_non_signature_kwargs,
     46     find_labels,
     47     flatten_dict,
     48     infer_framework,
     49     is_jax_tensor,
     50     is_numpy_array,
     51     is_tensor,
     52     is_tf_symbolic_tensor,
     53     is_tf_tensor,
     54     is_torch_device,
     55     is_torch_dtype,
     56     is_torch_tensor,
     57     reshape,
     58     squeeze,
     59     strtobool,
     60     tensor_size,
     61     to_numpy,
     62     to_py_obj,
     63     torch_float,
     64     torch_int,
     65     transpose,
     66     working_or_temp_dir,
     67 )
     68 from .hub import (
     69     CLOUDFRONT_DISTRIB_PREFIX,
     70     HF_MODULES_CACHE,
   (...)
     96     try_to_load_from_cache,
     97 )
     98 from .import_utils import (
     99     ACCELERATE_MIN_VERSION,
    100     ENV_VARS_TRUE_AND_AUTO_VALUES,
   (...)
    219     torch_only_method,
    220 )

File ~/.conda/envs/lsa/lib/python3.8/site-packages/transformers/utils/generic.py:32
     29 import numpy as np
     30 from packaging import version
---> 32 from .import_utils import (
     33     get_torch_version,
     34     is_flax_available,
     35     is_mlx_available,
     36     is_tf_available,
     37     is_torch_available,
     38     is_torch_fx_proxy,
     39 )
     42 class cached_property(property):
     43     """
     44     Descriptor that mimics @property but caches output in member variable.
     45 
   (...)
     48     Built-in in functools from Python 3.8.
     49     """

File ~/.conda/envs/lsa/lib/python3.8/site-packages/transformers/utils/import_utils.py:274
    272 _torch_fx_available = False
    273 if _torch_available:
--> 274     torch_version = version.parse(_torch_version)
    275     _torch_fx_available = (torch_version.major, torch_version.minor) >= (
    276         TORCH_FX_REQUIRED_VERSION.major,
    277         TORCH_FX_REQUIRED_VERSION.minor,
    278     )
    281 _torch_xla_available = False

File ~/.conda/envs/lsa/lib/python3.8/site-packages/packaging/version.py:52, in parse(version)
     43 def parse(version: str) -> "Version":
     44     """Parse the given version string.
     45 
     46     >>> parse('1.0.dev1')
   (...)
     50     :raises InvalidVersion: When the version string is not a valid version.
     51     """
---> 52     return Version(version)

File ~/.conda/envs/lsa/lib/python3.8/site-packages/packaging/version.py:196, in Version.__init__(self, version)
    185 """Initialize a Version object.
    186 
    187 :param version:
   (...)
    192     exception will be raised.
    193 """
    195 # Validate the version and parse it into pieces
--> 196 match = self._regex.search(version)
    197 if not match:
    198     raise InvalidVersion(f"Invalid version: '{version}'")

TypeError: expected string or bytes-like object`
