### ISSUE TITLE
Upgrade to SAM 2.1 

### ISSUE THREAD

**Issue by iamnotagentleman** [luca-medeiros/lang-segment-anything#78]
### Motivation & Examples

I have tested this locally, and it works as expected. The only challenge I encountered seems to be related to the configuration files—Hydra does not appear to detect version 2.1 files properly.

I'd be happy to volunteer to help prepare an update to address this issue.

**Comment by luca-medeiros** [comment]
Amazing. Didn't know about a 2.1. 
Go ahead! guess just update the commit hash and the dict with the configs should do the trick. Don't think 2.0 support is needed.

**Comment by iamnotagentleman** [comment]
Great. I am on it.

**Comment by arildgrimstveit** [comment]
Any progress on this? I am using SAM 2.1 for my project and it no longer works because it no longer finds the configs. I have not been able to figure out a fix yet.

**Comment by arildgrimstveit** [comment]
Apparently i had to use pip install without -e to import the packages into my environment and not using symbolic links.
