### ISSUE TITLE
No module Sam2

### ISSUE THREAD

**Issue by hasan1292** [luca-medeiros/lang-segment-anything#80]
### Motivation & Examples

I have been using langsam for almost an year. It worked like a charm. However, I installed recently on a new machine and I am getting this issue:

  File "/home/hasan/miniconda3/envs/latest_langsam/lib/python3.11/site-packages/lang_sam/models/sam.py", line 6, in <module>
    from sam2.automatic_mask_generator import SAM2AutomaticMaskGenerator
ModuleNotFoundError: No module named 'sam2'

Any idea, how to solve it?

**Comment by luca-medeiros** [comment]
How did you install it?
Recently lang-sam upgraded to SAM2. https://github.com/luca-medeiros/lang-segment-anything/pull/73

**Comment by hasan1292** [comment]
> How did you install it? Recently lang-sam upgraded to SAM2. #73

pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git

Used this command to install.

**Comment by luca-medeiros** [comment]
You might wanna check it now.
